[versions]
## Gradle Plugins
fix-javadoc = "1.19" # https://github.com/mfnalex/gradle-fix-javadoc-plugin
feather = "0.6.1" # https://github.com/ryderbelserion/Feather
shadow = "9.6.0" # https://github.com/GradleUp/shadow

[plugins]
# https://github.com/mfnalex/gradle-fix-javadoc-plugin
fix-javadoc = { id = "com.jeff-media.fix-javadoc-plugin", version.ref = "fix-javadoc" }

[libraries]
# https://github.com/ryderbelserion/Feather
feather = { module = "com.ryderbelserion.feather.core:com.ryderbelserion.feather.core.gradle.plugin", version.ref = "feather" }

# https://github.com/GradleUp/shadow
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[bundles]
build = [
    "feather",
    "shadow"
]